### PR TITLE
JSON schema validation and WOF document property normalisation

### PR DESCRIPTION
**Pull request by vicchi**
See whosonfirst/whosonfirst-json-schema#1 for details of this PR in context with other changes/pull requests.

### CODE REVIEW

**Review by thisisaaronland — APPROVED** [review]

**Comment by vicchi** [comment]
Nice! Thanks @thisisaaronland

**Comment by vicchi** [comment]
@thisisaaronland - have added some commits to this branch (re: the discussion on `wof:lang_x_spoken` and `wof:lang_x_official` ... these will need to be merged too.

New PR? Or shall I cherry pick merge?

**Comment by thisisaaronland** [comment]
Whatever is easiest for you. I am pretty much a barbarian when it comes to Git "elegance" ...

**Comment by vicchi** [comment]
@thisisaaronland Done; see commit `d31b99c` (now pushed to `master`)

**Pull request merged**
